channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scikit-learn
  - pandas
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - tqdm
  - seaborn
  - pip
  - nodejs
  - ipywidgets
  - pip:
    - plotnine
    - xlrd